[package]
name = "alicesaidhi/pebble"
exclude = ["aftman.toml", "test.project.json", "src/stories"]
version = "0.1.0-rc.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "centau/vide@0.3.1"