[package]
name = "alicesaidhi/pebble"
exclude = ["aftman.toml", "test.project.json", "src/stories"]
version = "0.1.0-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "aloroid/vide-with-types@0.2.4"
